language: node_js
node_js:
- 5.8
- 4.4
notifications:
  slack:
    secure: NLgiVFX/z9vlUbTpv3tdwq9OoPQFT8A5CajP6lgPcYayYrsvwMNH/3uJ41n3AX/KuIqait8EZh/XBB4TTBhsjJE9YDP5PM2SzSlPOw1MKa9HZrRXJ4BMkr3A5RZ7cpd35wPBasDNd0XzUINfRdWvN2jjAG1ifbYQUeJ0ogqSAioAte5COn5LO0zkufyKJSKgZpqxX9Hf7hKXtDdbvePhTSoE+NZePTaxKoN97c3/VnrTz8GGKnZRcKfbBYjGeY+trGwkFZlYXmNt140SVKp8VndFjZVceo0bc+YcmBkeg2m6GZm/XymXiHfzTE5oDZDw0MJzKICnjTvhGnJbRQj2PzOXrMbaAYHMIA3Uo9Or+ZTOkFW3eGbRZVoYQSClUxA8hyTiOeWDeSljM4c5SuKzQUTsC+N8q+5vZ3nPCMQp9MZ1FmV7ViEWgu5Zxr+nBU17YOa7EZXTzl5nYHBnjtOovCTNdZhtRdiY2oHEyHrOzsIzcu1M+B7d3kWxc6JXagELGeQmGlJPZWQrGJ+qIkoMYqzXtn42C9nqrkjN1uUWU5ZLT8RnZ4GJZKntmAZTMB8LMT2vLh+0q3W9DPV0IudDQCyXuy9BYmQzA/tK9yv5RvyxS2MgKFtNpC3NY4x0tjq07foVXe/+VRxA/bO2+BtpMAfmVKyWD2yO+k8ovOKeLCE=
