language: node_js
node_js:
- 5.8
- 4.4
before_install: if [[ `npm -v` != 3* ]]; then npm i -g npm@3; fi
install:
- npm install
- npm install react react-dom
notifications:
  slack:
    secure: MCswsB4fPAqdDoIye+yiglf9heYUqSYyfAy5P/TRfn8/iAWfQPLBhfil1SmVPMgzSygsPfoWhyd2ksB1LQ4ODQbWQ34H4K0BM8FDAG8GhPdYdhWcxNevGeoZWz07ww6Vl73H/pbNzo8HzYOrE4yWWXf7gqM8K7QiqFqPpWCjOs2R5HU+YfzapoWSKtpGhw2pc3Rpa0PCr5WcT3vFik+w3snJ/esUdI2JKSFl4RE4QdIYDk+Clr6RnsqX+RBLJ3VS/e2Xw8Lubn/jfGD6+AZZNFSx4qamXJ2E3x322SRaFEBZfVXxxXLARxnrulAwma8sd0Djz9NDwSRmza8dmuqpZiryJwIz5t3Yskfr8yZDHVsOcebGQ1RuxNrXhmXVjLd4ssz0ZaS3kuAsVlaqCjOj8uedEQOdjNunItqbbRUXvVwEDUzDmA7K5yKjUM+1mkVr5nSl6EW4dsgeHuzF80yRtzsGMiuf7ie9bAbpctun9VZarBbqYHMhhgMBP2TcYvXG3eIVkwq0Dq3zcAkIdNLNCNwfil3TMYXhr00dTziR0IrNezu6TsQw8H49V37xxoW/Fbn39fYdnMxMjw6SNtfxasxj65f+uzE6QsrRCNGRsk6blmuINWeThWDLHRWWi+XCTCTcvhTlFhTKaJU8ye2VsOgxJynrsO/D7Q6GT0SQZFo=
